import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import catalog from '@/data/circuits/catalog.json';
import index from '@/data/circuits/index.json';
import { locationSlug } from '@/lib/circuit-geometry';

/**
 * `catalog.json` is the points-free view of the 40 outline files: the grid's links and the detail
 * page's facts come from it so neither has to download an outline. It is generated by
 * `scripts/fetch-circuit-geometry.mjs` alongside the outlines, and this is what keeps the two in
 * step — a re-export that changes a circuit and not the catalog fails here.
 */
const DIR = resolve(__dirname, '..', 'data', 'circuits');
const OUTLINE_FILE = /^[a-z]{2}-\d{4}\.json$/;
const files = readdirSync(DIR).filter((name) => OUTLINE_FILE.test(name)).sort();
const LOCATION_TO_ID: Record<string, string> = index;

describe('catalog.json', () => {
  it('has exactly one entry per outline file, sorted by id', () => {
    expect(catalog.map((entry) => `${entry.id}.json`)).toEqual(files);
  });

  it.each(files)('agrees with %s on every field it copies', (file) => {
    const outline = JSON.parse(readFileSync(resolve(DIR, file), 'utf8')) as Record<string, unknown>;
    const entry = catalog.find((row) => `${row.id}.json` === file);
    expect(entry).toEqual({
      id: outline.id,
      slug: locationSlug(outline.location as string),
      name: outline.name,
      location: outline.location,
      lengthM: outline.lengthM,
      firstGp: outline.firstGp,
    });
  });

  it('gives every circuit a unique canonical slug that resolves back to it', () => {
    const slugs = catalog.map((entry) => entry.slug);
    expect(new Set(slugs).size).toBe(slugs.length);
    for (const entry of catalog) expect(LOCATION_TO_ID[entry.slug]).toBe(entry.id);
  });
});

describe('index.json', () => {
  it('only ever points at a circuit that has an outline file', () => {
    for (const id of Object.values(LOCATION_TO_ID)) expect(files).toContain(`${id}.json`);
  });

  /*
   * FastF1 spells these locations differently in seasons before 2026. Without them Abu Dhabi
   * 2020–25 (`Yas Island`) and every Belgian GP before 2022 (`Spa`) resolve to nothing — the
   * briefing band drew no outline for them, and the winners matcher would miss them.
   */
  it.each([
    ['yas-island', 'ae-2009'],
    ['abu-dhabi', 'ae-2009'],
    ['spa', 'be-1925'],
    ['nurburgring', 'de-1927'],
    ['mugello', 'it-1914'],
  ])('aliases the earlier-season spelling %s to %s', (slug, id) => {
    expect(LOCATION_TO_ID[slug]).toBe(id);
  });
});

/*
 * The backend reads `centroid` for the weather forecast: coordinates rather than geocoding a
 * `"{Location},{country}"` string, which turned Sepang into "Kuala Lumpur,BH" and every country
 * missing from a hand-kept map into "US". It is the mean of the same ring the outline is drawn
 * from, in WGS84 degrees, so it sits on the circuit rather than in the nearest city.
 */
describe('circuit centroids', () => {
  it.each(files)('%s carries a WGS84 centroid', (file) => {
    const outline = JSON.parse(readFileSync(resolve(DIR, file), 'utf8')) as {
      centroid?: { lat: number; lon: number };
    };
    expect(outline.centroid).toBeDefined();
    const { lat, lon } = outline.centroid!;
    expect(Math.abs(lat)).toBeLessThanOrEqual(90);
    expect(Math.abs(lon)).toBeLessThanOrEqual(180);
  });

  // Published coordinates of each track, hand-copied; a centroid of a lap is within ~2 km of them.
  it.each([
    ['it-1922', 45.6156, 9.2811],
    ['my-1999', 2.7606, 101.7381],
    ['us-2023', 36.1147, -115.1728],
    ['br-1940', -23.7036, -46.6997],
  ])('puts %s where the circuit is', (id, lat, lon) => {
    const outline = JSON.parse(readFileSync(resolve(DIR, `${id}.json`), 'utf8')) as {
      centroid: { lat: number; lon: number };
    };
    expect(Math.abs(outline.centroid.lat - lat)).toBeLessThan(0.03);
    expect(Math.abs(outline.centroid.lon - lon)).toBeLessThan(0.03);
  });
});
